# Generated by Django 4.2.20 on 2025-04-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0012_environment_labels_trainingportal_default_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="analytics_url",
            field=models.URLField(blank=True, null=True, verbose_name="analytics url"),
        ),
    ]
