# Generated by Django 4.2.20 on 2025-04-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0013_session_analytics_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="index_url",
            field=models.URLField(blank=True, null=True, verbose_name="index url"),
        ),
    ]
