# Generated by Django 4.2.20 on 2025-04-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0014_session_index_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="resource_name",
            field=models.CharField(
                default="", max_length=256, verbose_name="resource name"
            ),
        ),
    ]
